version: '3.1'
services:
  stats-server:
    build: ./stat-service/stat-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DATABASE_URL=jdbc:postgresql://stats-db:5432/stats_DB
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats_DB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ./main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - DATABASE_URL=jdbc:postgresql://ewm-db:5432/service_DB
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - STAT_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=service_DB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password